### ISSUE TITLE
What we do section tasks

### ISSUE THREAD

**Issue by eallenOP** [New-Zealand-Cadet-Forces/op-refresh#24]
What We Do- NZCF Training

- [ ] Smaller header image, could we show some training photos? #17 
- [ ] A couple of supporting images in the body of the text
- [x] Links in the last paragraph take you back to the page your already on
- [x] Can we move the call to action block up so it’s closer to the last line of text?

What we Do- Cadet Courses

- [ ] Supporting images and a smaller header image were the only pieces of feedback for here #17 

What we do- Duke of Ed

- [x] What We Do- Duke of Ed Can we remove this from the drop down menu? We’ll add them in as a supporter on the supporters page.

What we do- Overseas opportunities

- [ ] Supporting images and a smaller header image with cadets overseas as the images for this page #17 
- [x] The logos in the body of the text didn’t load
 
What we do- Officer Courses

- [ ] Supporting images and a smaller header image were the only pieces of feedback for here #17 . I’ll drop some officer images into that folder, this doesn’t look to have been done.
